package com.daigou.sg.rpc.tpackage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TArrangeDeliveryPackage extends BaseModule<TArrangeDeliveryPackage> implements Serializable {
    public int arrivedCount;
    public int notArrivedCount;
    public ArrayList<TPackage> packages;
}
