package com.daigou.sg.rpc.tpackage;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TArrangeDeliveryBill implements Serializable {
    public double totalFee;
    public ArrayList<TPackageDetail> packageBills;
    public boolean couponUsed;
    public String couponErrorMessage;

    static TArrangeDeliveryBill fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TArrangeDeliveryBill Object");
        }

        return doFromJSON(jp);
    }

    private static TArrangeDeliveryBill doFromJSON(JsonParser jp) throws IOException {
        TArrangeDeliveryBill result = new TArrangeDeliveryBill();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("totalFee")) {
                jp.nextToken();
                result.totalFee = jp.getDoubleValue();
            } else if (fieldName.equals("packageBills")) {
                result.packageBills = TPackageDetail.fromJSONArray(jp);
            } else if (fieldName.equals("couponUsed")) {
                jp.nextToken();
                result.couponUsed = jp.getBooleanValue();
            } else if (fieldName.equals("couponErrorMessage")) {
                jp.nextToken();
                result.couponErrorMessage = jp.getText();
            }
        }
        return result;
    }

    static ArrayList<TArrangeDeliveryBill> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TArrangeDeliveryBill array");
        }

        ArrayList<TArrangeDeliveryBill> result = new ArrayList<TArrangeDeliveryBill>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
