package com.daigou.sg.rpc.tpackage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCompletedPackage extends BaseModule<TCompletedPackage> implements Serializable {
    public int customerCommentId;
    public String satisfaction;
    public String caption;
    public String comment;
    public ArrayList<TPackage> packages;
}
