package com.daigou.sg.rpc.tpackage;

import com.daigou.sg.rpc.BaseModule;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TInvoice extends BaseModule<TInvoice> implements Serializable {
	@SerializedName("package")
    public TPackage tPackage;
    public com.daigou.sg.rpc.payment.TPaymentBill paymentBill;
}
