// Code generated by go-bindata.
// sources:
// tmpl/golang/echo_module.gogo
// tmpl/golang/include.gogo
// tmpl/golang/service.gogo
// tmpl/golang/services_file.gogo
// tmpl/golang/struct.gogo
// tmpl/golang/structs_file.gogo
// DO NOT EDIT!

package gotpl

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// tmplGolangEcho_moduleGogo reads file data from disk. It returns an error on failure.
func tmplGolangEcho_moduleGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/echo_module.gogo"
	name := "tmpl/golang/echo_module.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplGolangIncludeGogo reads file data from disk. It returns an error on failure.
func tmplGolangIncludeGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/include.gogo"
	name := "tmpl/golang/include.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplGolangServiceGogo reads file data from disk. It returns an error on failure.
func tmplGolangServiceGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/service.gogo"
	name := "tmpl/golang/service.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplGolangServices_fileGogo reads file data from disk. It returns an error on failure.
func tmplGolangServices_fileGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/services_file.gogo"
	name := "tmpl/golang/services_file.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplGolangStructGogo reads file data from disk. It returns an error on failure.
func tmplGolangStructGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/struct.gogo"
	name := "tmpl/golang/struct.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplGolangStructs_fileGogo reads file data from disk. It returns an error on failure.
func tmplGolangStructs_fileGogo() (*asset, error) {
	path := "/Users/dtynn/work/devgopj/src/github.com/ezbuy/tgen/tmpl/golang/structs_file.gogo"
	name := "tmpl/golang/structs_file.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"tmpl/golang/echo_module.gogo": tmplGolangEcho_moduleGogo,
	"tmpl/golang/include.gogo": tmplGolangIncludeGogo,
	"tmpl/golang/service.gogo": tmplGolangServiceGogo,
	"tmpl/golang/services_file.gogo": tmplGolangServices_fileGogo,
	"tmpl/golang/struct.gogo": tmplGolangStructGogo,
	"tmpl/golang/structs_file.gogo": tmplGolangStructs_fileGogo,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"tmpl": &bintree{nil, map[string]*bintree{
		"golang": &bintree{nil, map[string]*bintree{
			"echo_module.gogo": &bintree{tmplGolangEcho_moduleGogo, map[string]*bintree{}},
			"include.gogo": &bintree{tmplGolangIncludeGogo, map[string]*bintree{}},
			"service.gogo": &bintree{tmplGolangServiceGogo, map[string]*bintree{}},
			"services_file.gogo": &bintree{tmplGolangServices_fileGogo, map[string]*bintree{}},
			"struct.gogo": &bintree{tmplGolangStructGogo, map[string]*bintree{}},
			"structs_file.gogo": &bintree{tmplGolangStructs_fileGogo, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

