package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcel extends BaseModule<TParcel> implements Serializable {
    public String userName;
    public String phone;
    public String parcelNumber;
    public String status;
    public ArrayList<TParcelSection> sections;
}
