package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelSection extends BaseModule<TParcelSection> implements Serializable {
    public String name;
	@SerializedName("package")
    public String tPackage;
    public long value;
}
