package com.daigou.sg.rpc.tpackage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPackageSummary extends BaseModule<TPackageSummary> implements Serializable {
    public int pendingReplyCount;
    public int prepareShipmentCount;
    public int shippedCount;
    public int arrangeDeliveryCount;
    public int pendingPaymentCount;
    public int pendingDeliveryCount;
    public int acknowledgeCount;
    public int completedCount;
}
