package com.daigou.sg.rpc.tpackage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPendingDeliveryPackage extends BaseModule<TPendingDeliveryPackage> implements Serializable {
    public int shipmentId;
    public String localDeliveryMethod;
    public String stationName;
    public String periodName;
    public String localDeliveryDate;
    public String shipToAddress;
    public boolean canBeEdited;
    public int mrtStationItemId;
    public int neighbourhoodStationItemId;
    public int selfStationId;
    public double totalFee;
    public ArrayList<TPackage> packages;
}
