package com.daigou.sg.rpc.category;

import com.daigou.sg.rpc.BaseModule;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProductSimple extends BaseModule<TProductSimple> implements Serializable {

    public String url;
    public String name;
    public String price;
    public String picture;
    public int favouriteCount;
    public String priceWithSymbol;
    public String originCode;
    public String vendorName;
    public String altProductName;
    public String customerLocalPrice;
    public boolean isEzBuy;
    
}
