package com.daigou.sg.rpc.order;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEzShipping implements Serializable {
    public boolean on;
    public ArrayList<String> description;

    static TEzShipping fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TEzShipping Object");
        }

        return doFromJSON(jp);
    }

    private static TEzShipping doFromJSON(JsonParser jp) throws IOException {
        TEzShipping result = new TEzShipping();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("on")) {
                jp.nextToken();
                result.on = jp.getBooleanValue();
            } else if (fieldName.equals("description")) {
                result.description = JsonUtils.readStringList(jp);
            }
        }
        return result;
    }

    static ArrayList<TEzShipping> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TEzShipping array");
        }

        ArrayList<TEzShipping> result = new ArrayList<TEzShipping>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
