package com.daigou.sg.rpc.payment;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimePaymentSummary implements Serializable {
    public ArrayList<TPrimeType> primeTypes;
    public String tip;
    public String prepay;
    public boolean isPrimeMonthlyBought;
    public boolean isPrimeYearlyBought;

    static TPrimePaymentSummary fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TPrimePaymentSummary Object");
        }

        return doFromJSON(jp);
    }

    private static TPrimePaymentSummary doFromJSON(JsonParser jp) throws IOException {
        TPrimePaymentSummary result = new TPrimePaymentSummary();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("primeTypes")) {
                result.primeTypes = TPrimeType.fromJSONArray(jp);
            } else if (fieldName.equals("tip")) {
                jp.nextToken();
                result.tip = jp.getText();
            } else if (fieldName.equals("prepay")) {
                jp.nextToken();
                result.prepay = jp.getText();
            } else if (fieldName.equals("isPrimeMonthlyBought")) {
                jp.nextToken();
                result.isPrimeMonthlyBought = jp.getBooleanValue();
            } else if (fieldName.equals("isPrimeYearlyBought")) {
                jp.nextToken();
                result.isPrimeYearlyBought = jp.getBooleanValue();
            }
        }
        return result;
    }

    static ArrayList<TPrimePaymentSummary> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TPrimePaymentSummary array");
        }

        ArrayList<TPrimePaymentSummary> result = new ArrayList<TPrimePaymentSummary>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
