package com.daigou.sg.rpc.shipforme;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipForMeOrderHomeSummary implements Serializable {
    public int cnCount;
    public int twCount;
    public int usCount;

    static TShipForMeOrderHomeSummary fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TShipForMeOrderHomeSummary Object");
        }

        return doFromJSON(jp);
    }

    private static TShipForMeOrderHomeSummary doFromJSON(JsonParser jp) throws IOException {
        TShipForMeOrderHomeSummary result = new TShipForMeOrderHomeSummary();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("cnCount")) {
                jp.nextToken();
                result.cnCount = jp.getIntValue();
            } else if (fieldName.equals("twCount")) {
                jp.nextToken();
                result.twCount = jp.getIntValue();
            } else if (fieldName.equals("usCount")) {
                jp.nextToken();
                result.usCount = jp.getIntValue();
            }
        }
        return result;
    }

    static ArrayList<TShipForMeOrderHomeSummary> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TShipForMeOrderHomeSummary array");
        }

        ArrayList<TShipForMeOrderHomeSummary> result = new ArrayList<TShipForMeOrderHomeSummary>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
