package com.daigou.sg.rpc.shipforme;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipformeAddress implements Serializable {
    public String warehouse;
    public String name;
    public String area;
    public String address;
    public String zipcode;
    public String phoneNumber;

    static TShipformeAddress fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TShipformeAddress Object");
        }

        return doFromJSON(jp);
    }

    private static TShipformeAddress doFromJSON(JsonParser jp) throws IOException {
        TShipformeAddress result = new TShipformeAddress();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("warehouse")) {
                jp.nextToken();
                result.warehouse = jp.getText();
            } else if (fieldName.equals("name")) {
                jp.nextToken();
                result.name = jp.getText();
            } else if (fieldName.equals("area")) {
                jp.nextToken();
                result.area = jp.getText();
            } else if (fieldName.equals("address")) {
                jp.nextToken();
                result.address = jp.getText();
            } else if (fieldName.equals("zipcode")) {
                jp.nextToken();
                result.zipcode = jp.getText();
            } else if (fieldName.equals("phoneNumber")) {
                jp.nextToken();
                result.phoneNumber = jp.getText();
            }
        }
        return result;
    }

    static ArrayList<TShipformeAddress> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TShipformeAddress array");
        }

        ArrayList<TShipformeAddress> result = new ArrayList<TShipformeAddress>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
