/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

import Foundation

public final class TREExample: EzObject {
    public var amountAvailable: Double = 0.0

    public var rebateAmountAvailable: String?

    public var amountPendingVerification: Bool = false

    public var pendingWithdrawAmount: Int = 0

    public var serviceType: TREServiceType?

    public var unpaidAmount: Int64 = 0

    public var fooes: [TREFoo]?

    public var strs: [String]?

    public var ints: [Int]?

    public var basics: [TRSharedBasic]?

    @nonobjc
    public var int64s:[Int64]? {
        didSet {
            objc_int64s = int64s?.map { value in NSNumber(longLong: value) }
        }
    }

    @objc(int64s)
    public var objc_int64s:[NSNumber]?

    public override var allKeys: Set<String> {
        return ["amountAvailable", "rebateAmountAvailable", "amountPendingVerification", "pendingWithdrawAmount", "serviceType", "unpaidAmount", "fooes", "strs", "ints", "basics", "int64s"]
    }

    public override func fromJSON(jsonObject: AnyObject?) -> Bool {
        guard super.fromJSON(jsonObject) else { return false }

        guard let dict = jsonObject as? [String: AnyObject] else { return false }
        amountAvailable = dict["amountAvailable"] as? Double ?? 0.0
        rebateAmountAvailable = dict["rebateAmountAvailable"] as? String
        amountPendingVerification = dict["amountPendingVerification"] as? Bool ?? false
        pendingWithdrawAmount = dict["pendingWithdrawAmount"] as? Int ?? 0
        serviceType = TREServiceType(code: dict["serviceType"] as? Int)
        unpaidAmount = (dict["unpaidAmount"] as? NSNumber)?.longLongValue ?? 0
        fooes = [TREFoo](jsonObject: dict["fooes"])
        strs = dict["strs"] as? [String]
        ints = dict["ints"] as? [Int]
        basics = [TRSharedBasic](jsonObject: dict["basics"])
        int64s = (dict["int64s"] as? [NSNumber])?.map { value in value.longLongValue }

        return true
    }

    public override func toJSON() -> AnyObject {
        var dict = [String: AnyObject]()
        dict["amountAvailable"] = amountAvailable
        dict["rebateAmountAvailable"] = rebateAmountAvailable
        dict["amountPendingVerification"] = amountPendingVerification
        dict["pendingWithdrawAmount"] = pendingWithdrawAmount
        dict["serviceType"] = serviceType?.rawValue
        dict["unpaidAmount"] = NSNumber(longLong: unpaidAmount)
        dict["fooes"] = fooes?.toJSON()
        dict["strs"] = strs
        dict["ints"] = ints
        dict["basics"] = basics?.toJSON()
        dict["int64s"] = int64s?.map { value in NSNumber(longLong: value) }

        return dict
    }
}
