package com.daigou.sg.rpc.order;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderItem extends BaseModule<TOrderItem> implements Serializable {
    public String sku;
    public String skuPrice;
    public String localSkuPrice;
    public int qty;
}
