package com.daigou.sg.rpc.order;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderDetail extends BaseModule<TOrderDetail> implements Serializable {
    public int id;
    public String orderNumber;
    public String orderStatus;
    public String productName;
    public String productImage;
    public String unitPrice;
    public double localUnitPrice;
    public int qty;
    public boolean insured;
    public int shipmentTypeId;
    public String altShipmentTypeName;
    public String shipmentTypeCode;
    public String productRemark;
    public boolean canEdit;
    public String warehouseCode;
    public String sellerDiscount;
    public ArrayList<com.daigou.sg.rpc.payment.TPaymentBillCategory> orderBillDetails;
    public ArrayList<TOrderRemark> orderRemarks;
    public ArrayList<TOrderItem> orderItems;
    public double localInternalShipmentFee;
    public double totalPrice;
    public String originCode;
    public String productUrl;
}
