package com.daigou.sg.rpc.order;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderItem implements Serializable {
    public String sku;
    public String skuPrice;
    public String localSkuPrice;
    public int qty;

    static TOrderItem fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TOrderItem Object");
        }

        return doFromJSON(jp);
    }

    private static TOrderItem doFromJSON(JsonParser jp) throws IOException {
        TOrderItem result = new TOrderItem();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("sku")) {
                jp.nextToken();
                result.sku = jp.getText();
            } else if (fieldName.equals("skuPrice")) {
                jp.nextToken();
                result.skuPrice = jp.getText();
            } else if (fieldName.equals("localSkuPrice")) {
                jp.nextToken();
                result.localSkuPrice = jp.getText();
            } else if (fieldName.equals("qty")) {
                jp.nextToken();
                result.qty = jp.getIntValue();
            }
        }
        return result;
    }

    static ArrayList<TOrderItem> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TOrderItem array");
        }

        ArrayList<TOrderItem> result = new ArrayList<TOrderItem>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
