package com.daigou.sg.rpc.shipforme;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipformeAddress extends BaseModule<TShipformeAddress> implements Serializable {
    public String warehouse;
    public String name;
    public String area;
    public String address;
    public String zipcode;
    public String phoneNumber;
}
