package com.daigou.sg.rpc.shipforme;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipForMeOrderSummary extends BaseModule<TShipForMeOrderSummary> implements Serializable {
    public int notReceivedCount;
    public int problemOrdersCount;
    public int notReplyProblemOrdersCount;
    public int orderInParcelCount;
    public int historyCount;
    public int readyToShipSHCount;
    public int readyToShipGZCount;
    public int readyToShipTWCount;
    public int readyToShipUSCount;
}
