package com.daigou.sg.rpc.shipforme;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipForMeOrderHomeSummary extends BaseModule<TShipForMeOrderHomeSummary> implements Serializable {
    public int cnCount;
    public int twCount;
    public int usCount;
}
