package com.daigou.sg.rpc.payment;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPaymentBillCategory implements Serializable {
    public String billCategoryCode;
    public String billCategoryName;
    public String altBillCategoryName;
    public String total;

    static TPaymentBillCategory fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TPaymentBillCategory Object");
        }

        return doFromJSON(jp);
    }

    private static TPaymentBillCategory doFromJSON(JsonParser jp) throws IOException {
        TPaymentBillCategory result = new TPaymentBillCategory();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("billCategoryCode")) {
                jp.nextToken();
                result.billCategoryCode = jp.getText();
            } else if (fieldName.equals("billCategoryName")) {
                jp.nextToken();
                result.billCategoryName = jp.getText();
            } else if (fieldName.equals("altBillCategoryName")) {
                jp.nextToken();
                result.altBillCategoryName = jp.getText();
            } else if (fieldName.equals("total")) {
                jp.nextToken();
                result.total = jp.getText();
            }
        }
        return result;
    }

    static ArrayList<TPaymentBillCategory> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TPaymentBillCategory array");
        }

        ArrayList<TPaymentBillCategory> result = new ArrayList<TPaymentBillCategory>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
