/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

import Foundation

public final class BasicService: NSObject {

    public class func getBasic(key: Int, id: Int64, success: (TRSharedBasic) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "Basic.getBasic"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success(TRSharedBasic(jsonObject: responseObject)!)
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    public class func getBasics(key: Int, id: Int64, int64s: [Int64]?, success: ([TRSharedBasic]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)
        params["int64s"] = int64s?.map { value in NSNumber(longLong: value) }

        let api = "Basic.getBasics"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success([TRSharedBasic](jsonObject: responseObject) ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    public class func getCommons(key: Int, id: Int64, success: ([TRCommonCommon]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "Basic.getCommons"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success([TRCommonCommon](jsonObject: responseObject) ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    public class func getInt64s(id: Int64, int64s: [Int64]?, success: ([Int64]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["id"] = NSNumber(longLong: id)
        params["int64s"] = int64s?.map { value in NSNumber(longLong: value) }

        let api = "Basic.getInt64s"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success((responseObject as? [NSNumber])?.map { value in value.longLongValue } ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

}
