/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

import Foundation

class BasicService: NSObject {

    class func getBasic(key: Int, id: Int64, success: (TRSharedBasic) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "Basic.getBasic"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success(TRSharedBasic(jsonObject: responseObject)!)
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getBasics(key: Int, id: Int64, success: ([TRSharedBasic]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "Basic.getBasics"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success([TRSharedBasic](jsonObject: responseObject) ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getCommons(key: Int, id: Int64, success: ([TRCommonCommon]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "Basic.getCommons"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success([TRCommonCommon](jsonObject: responseObject) ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

}
