/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

import Foundation

class BasicService: NSObject {

    class func getAges(id: Int64, success: ([Int]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["id"] = NSNumber(longLong: id)

        let api = "BasicService.getAges"

        debugPrint("api", " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject);
            
            success(jsonObject as? [Int] ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getNames(success: ([String]) -> Void, failure: ((NSError) -> Void)? = nil) {
        let params = [String: AnyObject]()
        let api = "BasicService.getNames"

        debugPrint("api", " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject);
            
            success(jsonObject as? [String] ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getObjects(key: Int, id: Int64, success: ([TBasic]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "BasicService.getObjects"

        debugPrint("api", " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject);
            
            success([TBasic](jsonObject: responseObject) ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getStruct(key: Int, id: Int64, success: (TBasic) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["key"] = key
        params["id"] = NSNumber(longLong: id)

        let api = "BasicService.getStruct"

        debugPrint("api", " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject);
            
            success(TBasic(jsonObject: responseObject)!)
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

}
