/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

import Foundation

class CommonService: NSObject {

    class func getAges(id: Int64, success: ([Int]) -> Void, failure: ((NSError) -> Void)? = nil) {
        var params = [String: AnyObject]()
        params["id"] = NSNumber(longLong: id)

        let api = "Common.getAges"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success(responseObject as? [Int] ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

    class func getNames(success: ([String]) -> Void, failure: ((NSError) -> Void)? = nil) {
        let params = [String: AnyObject]()
        let api = "Common.getNames"

        debugPrint(api, " req: ", params)

        AreaService.current?.JSRONPRCClient.invokeMethod(api, withParameters: params, success: { (operation, responseObject) -> Void in
            debugPrint(api, " resp: ", responseObject)
            
            success(responseObject as? [String] ?? [])
            }, failure: { (operation, error) -> Void in
                failure?(error)
        })
    }

}
