package com.daigou.sg.rpc.order;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEzShipping extends BaseModule<TEzShipping> implements Serializable {
    public boolean on;
    public ArrayList<String> description;
}
