package com.daigou.sg.rpc.category;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCategory implements Serializable {
    public int id;
    public long pid;
    public String name;
    public boolean testbool;
    public double weight;

    static TCategory fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TCategory Object");
        }

        return doFromJSON(jp);
    }

    private static TCategory doFromJSON(JsonParser jp) throws IOException {
        TCategory result = new TCategory();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("id")) {
                jp.nextToken();
                result.id = jp.getIntValue();
            } else if (fieldName.equals("pid")) {
                jp.nextToken();
                result.pid = jp.getLongValue();
            } else if (fieldName.equals("name")) {
                jp.nextToken();
                result.name = jp.getText();
            } else if (fieldName.equals("testbool")) {
                jp.nextToken();
                result.testbool = jp.getBooleanValue();
            } else if (fieldName.equals("weight")) {
                jp.nextToken();
                result.weight = jp.getDoubleValue();
            }
        }
        return result;
    }

    static ArrayList<TCategory> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TCategory array");
        }

        ArrayList<TCategory> result = new ArrayList<TCategory>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
