package com.daigou.selfstation.rpc.selfstation;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TLoginResult implements Serializable {
    public boolean isSuccessful;
    public String token;
    public ArrayList<String> StationNames;

    static TLoginResult fromJSON(JsonParser jp) throws IOException {
        // Sanity check: verify that we got "Json Object":
        if (jp.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Expected data to start with a TLoginResult Object");
        }

        return doFromJSON(jp);
    }

    private static TLoginResult doFromJSON(JsonParser jp) throws IOException {
        TLoginResult result = new TLoginResult();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String fieldName = jp.getCurrentName();

            if (false) {
            } else if (fieldName.equals("isSuccessful")) {
                jp.nextToken();
                result.isSuccessful = jp.getBooleanValue();
            } else if (fieldName.equals("token")) {
                jp.nextToken();
                result.token = jp.getText();
            } else if (fieldName.equals("StationNames")) {
                result.StationNames = JsonUtils.readStringList(jp);
            }
        }
        return result;
    }

    static ArrayList<TLoginResult> fromJSONArray(JsonParser jp) throws IOException {
        if (jp.nextToken() != JsonToken.START_ARRAY) {
            throw new IOException("Expected data to start with a TLoginResult array");
        }

        ArrayList<TLoginResult> result = new ArrayList<TLoginResult>();

        // Iterate over object fields:
        while (jp.nextToken() != JsonToken.END_ARRAY) {
            result.add(doFromJSON(jp));
        }
        return result;
    }
}
