package com.daigou.sg.rpc.payment;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPaymentBillSummary extends BaseModule<TPaymentBillSummary> implements Serializable {
    public int id;
    public String paymentNumber;
    public String createDate;
    public double total;
    public String type;
    public String paymentType;
    public int shipmentId;
}
