package com.daigou.sg.rpc.payment;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimePaymentSummary extends BaseModule<TPrimePaymentSummary> implements Serializable {
    public ArrayList<TPrimeType> primeTypes;
    public String tip;
    public String prepay;
    public boolean isPrimeMonthlyBought;
    public boolean isPrimeYearlyBought;
}
